name: Deploy EKS with Cilium ENI Mode

on:
  push:
    branches: [main]

env:
  TF_WORKING_DIR: .
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GHA_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      ############################################
      # Step 1: Apply EKS Cluster (no nodes)
      ############################################
      - name: Terraform Apply - EKS Cluster Only
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
            -target=module.eks.cluster

      ############################################
      # Step 2: Apply Cilium + Node Groups
      ############################################
      - name: Terraform Apply - Cilium + Node Groups
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
            -target=module.eks.node_groups \
            -target=helm_release.cilium

      ############################################
      # Step 3: Add-ons (CoreDNS, etc)
      ############################################
      - name: Terraform Apply - Add-ons
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve
