name: Deploy EKS with Cilium ENI Mode

on:
  push:
    branches: [main]

env:
  TF_WORKING_DIR: .
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GHA_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (reconfigure backend)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -reconfigure

      ############################################
      # Step 1: Create EKS Cluster (no nodes/addons)
      ############################################
      - name: Terraform Apply - Cluster Only
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
            -var="enable_node_groups=false" \
            -var="enable_eks_addons=false" \
            -var="install_cilium=false"

      ############################################
      # Step 2: Create Node Groups + Cilium (ENI mode)
      ############################################
      - name: Terraform Apply - Node Groups + Cilium
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
            -var="enable_node_groups=true" \
            -var="enable_eks_addons=false" \
            -var="install_cilium=true"

      ############################################
      # Step 3: Add-ons (CoreDNS, EBS CSI, ALB, etc.)
      ############################################
      - name: Terraform Apply - Helm Add-ons
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
            -var="enable_node_groups=true" \
            -var="enable_eks_addons=true" \
            -var="install_cilium=true"
